// Generated by scripts/build-dataset.ts -- do not edit.
/** Monotonic YYYYMMDDNN version of the bundled fallback database. */
export const BUNDLED_DATABASE_VERSION = 2026083101;
/** SHA-256 of the exact compact payload reconstructed from committed sources. */
export const BUNDLED_DATABASE_PAYLOAD_SHA256 = '7146c919b065e6801c80eeee1d1851db4e8ba73fb68a3e87a494cf356a730ec1';
