// Generated by scripts/build-dataset.ts -- do not edit.
/** Monotonic YYYYMMDDNN version of the bundled fallback database. */
export const BUNDLED_DATABASE_VERSION = 2026082401;
/** SHA-256 of the exact UTF-8 bytes in data/database.payload.json. */
export const BUNDLED_DATABASE_PAYLOAD_SHA256 = '2eae5dd8105242154aedc335f79f612b3368f3520572144db5a20a5efe10740e';
