// Generated by scripts/build-dataset.ts -- do not edit.
/** Monotonic YYYYMMDDNN version of the bundled fallback database. */
export const BUNDLED_DATABASE_VERSION = 2026082402;
/** SHA-256 of the exact compact payload reconstructed from committed sources. */
export const BUNDLED_DATABASE_PAYLOAD_SHA256 = '6da1401e42b7f62591fa0d2fcee8bf60a0da91befd9c4746eb2d8376dbf63bd0';
